services:
  userservice:
    build:
      context: userservice
      dockerfile: Dockerfile
    image: userservice
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://userservice-db:5432/userservice-db
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - userservice-db

  memeservice:
    build:
      context: memeservice
      dockerfile: Dockerfile
    image: memeservice
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://memeservice-db:5432/memeservice-db
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - memeservice-db

  memecategoryservice:
    build:
      context: categoryservice
      dockerfile: Dockerfile
    image: categoryservice
    ports:
      - "8083:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://memecategoryservice-db:5432/memecategoryservice-db
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - memecategoryservice-db

  userservice-db:
    image: postgres:latest
    container_name: userservice-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: userservice-db
    ports:
      - "5433:5432"

  memeservice-db:
    image: postgres:latest
    container_name: memeservice-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: memeservice-db
    ports:
      - "5434:5432"

  memecategoryservice-db:
    image: postgres:latest
    container_name: memecategoryservice-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: memecategoryservice-db
    ports:
      - "5435:5432"
